version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile-melodic
    ipc: host
    security_opt:
    - seccomp:unconfined
    volumes:
    - workspace:/workspace
    environment:
    - DISPLAY=:0
    - ROS_MASTER_URI=http://simulator:11311/
  simulator:
    build:
      context: .
      dockerfile: Dockerfile-simulator
    ipc: host
    security_opt:
    - seccomp:unconfined
    environment:
    - DISPLAY=:0
volumes:
  workspace:
